name: CI-CD-Airflow

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest -q

  sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        with:
          args: >
            -Dsonar.projectKey=bank_marketing
            -Dsonar.organization=my-org
            -Dsonar.host.url=${{ secrets.SONAR_HOST }}
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

  docker:
    runs-on: ubuntu-latest
    needs: [tests, sonar]
    steps:
      - uses: actions/checkout@v3
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Build & Push Image
        run: |
          docker build -t ${{ secrets.DOCKER_USER }}/airflow:2.8.1 .
          docker push ${{ secrets.DOCKER_USER }}/airflow:2.8.1

  deploy:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Deploy Airflow (Docker)
        run: |
          docker run -d --name airflow \
            -p 8080:8080 \
            ${{ secrets.DOCKER_USER }}/airflow:2.8.1 webserver
